<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    
    // PRODUCTO
    /*App\Product::create([
      'name' => 'ASPIRINA PRUEBA 100 gr.',
      'catalog_product_id'=>1,
      'description' => 'DESCRIPCIÓN ASPIRINA PRUEBA 100 gr.',
      'state' => 'ACTIVO'
    ]); */
    //MEDICAMENTOS
    App\Product::create([       'name' => 'AGUJAS NIPRO (25G x 5/8) x 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'COLECTOR NIPRO DE HECES ESTERIL ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CREMER VENDAS YESO 8CM ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CREMER VENDAS YESO 10CM ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AGUJAS NIPRO (22G x 11/2) x 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MICROPORE CREMER BEIGE 1.20CMX10M ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BRANULAS NIPRO Nro. 22 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BRANULAS NIPRO Nro. 18 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AGUJAS NIPRO (22G x 1) x 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AGUJAS NIPRO (23G x 1) x 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AGUJAS NIPRO (18G x 1/2) x 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ECOPORE BLANCO 2.5 X 5 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'RANITIDINA 150 MG X 100 COMP. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'RANITIDINA 300 MG X 100 COMP. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AGUJAS NIPRO (21G x 11/2) x 100 UND ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'COLECTOR DE ORINA NIPRO ESTERIL ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BRANULAS NIPRO Nro. 24 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'SONDA FOLEY Nro. 14 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'SONDA FOLEY Nro. 16 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'SONDA FOLEY Nro. 18 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MICROPORE CREMER BEIGE 1.20CMX4.5M ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MICROPORE CREMER BEIGE 10CMX10M ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MICROPORE CREMER BEIGE 2.5CMX0.9M ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MICROPORE CREMER BEIGE 2.5CMX10M ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'JERINGAS NIPRO DE INSULINA ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'PARACETAMOL 500 Mg X 500 UND ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AGUJAS NIPRO (21G x 1) x 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BRANULAS NIPRO Nro. 20 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MICROPORE CREMER BEIGE 2.5CMX4.5M ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MICROPORE CREMER BEIGE 5CMX10M ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MICROPORE CREMER BEIGE 5CMX4.5M ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'EQUIPOS DE SUERO S/AGUJA NEO VAC ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BRANULAS NIPRO Nro. 14 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BRANULAS NIPRO Nro. 16 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AGUJAS NIPRO (23G x 11/2) x 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CREMER VENDAS YESO 15CM ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CREMER VENDAS YESO 20CM ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CREMER VENDAS YESO 12CM ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ESPARADRAPO 2.50CM x 0.90 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ESPARADRAPO 1.2CM x 4.50 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ESPARADRAPO 2.50CM x 4.50 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ESPARADRAPO 5CM x 4.50 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ESPARADRAPO 10CM x 4.50 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS DE YESO 20CM x 4M ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AGUJAS NIPRO (20G x 11/2) x 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'COTONETES CREMER X 75 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'SALES DE REHIDRATACION X 50 SOB. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CIPROFLOXACINA USP 500 MG ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CETIRIZINA 10 MG X 100 COMP. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ESPIRONOLACTONA 100 MGX 30 COMP. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ACICLOVIR 800 MG X 10 COMP. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BOLSA ORINA PEDIATRICA 100 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS DE GASA DE 15 CM x 12 und ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'Q-BAC 250 MG SUSP. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ESOFLUX CAJA x 14 COMP. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AGUJAS NIPRO (20G x 1) x 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'EQUIPOS DE SUERO C/AGUJA X 25 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'SONDA FOLEY Nro. 16 NIPRO ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'SONDA FOLEY Nro. 18 NIPRO ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ANTICOLESTEROL  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALCACHOFA MENTOLADA  INFUSIÓN x20 SAQ. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CEREBRAL  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BOLDO  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ANTIREMÁTICO INFUSIÓN',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALCACHOFA SUPRA x 25 CAP ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'SANA PROST SUPRA x 30 CAP ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'PECTORAL  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ZARZAPARRILLA  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ANTIDIABETICO  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALIVIAFEM  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALIVIAFEM SUPRA x 30 CAP ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'SEDANTE ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'REGULAX ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'TILO  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALCACHOFA MENTOLADA  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'HEPATO BILIAR  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'TRANQUILIZANTE ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ADELGAZANTE  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'RENAL  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'SANAPROST  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'DRENABON - ROMPE PIEDRA ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'DESINTOXICANTE  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'UÑA DE GATO  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AJO SUPRA x 25 CAP ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'QUITA PENA ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GASTRICO ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'LONGEVID SUPRA ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MANZANILLA ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'HERBOGASTROL  INFUSIÓN ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'LENOR TABLETAS CAJA X 10 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AMOXICILINA 500 MG x 500 CAPS ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'FERRO VITAMPLIA JBE X 240 ML. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'NOVATEST TEST DE EMBARAZO x 100 UNID. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'FOSFO- TONICO 120 ML. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GENTIBIOT SOL.30 ML. RIFAMICINA AL 1% ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VITAMPLIA PRENATAL x 30 GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'DICLOFENACO -75MG X 100 AMPOLLAS ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'COMPLEJO B x 100 AMPOLLAS ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'DEXAMETASONA FOSFATO x 100 AMPOLLAS ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CIPROFLOXACINA 500 MG x 100 CAPS ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AZITROMICINA 200 MG. 5MLX 1 SUSPENCION ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'TADALAFIL 20 MG x 4 CAPS ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'SILDENAFIL 100 MG x 4 CAPS ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'IBUPROFENO 800 Mg. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'IBUPROFENO 600 Mg ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GLIBENCLAMIDA 5 Mg ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'DICLOFENACO 100 mg x 1000 comp ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CARBAMAZEPINA 200 mg x 100 comp ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'IBUPROFENO 400 mg ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'DICLOFENACO GEL 1% ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CLOTRIMAZOL 1% CREMA SAPHI ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'IBUPROFENO 400 MG X 500 COMP SAPHI ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'DICLOFENACO 50MGX500COMP SAPHI ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'JERINGAS DE 50ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'LEVOFLOXACINA COMPRIMIDO 750 MG ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'DOLO - AGTRES COMPRIMIDO ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'IBUPROFENO C/ PARACETAMOL 100 COMP ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'IBUPROFENO C/PARACETAMOL 100 MG SUSP ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ANTITUSIGENO SUSPENSION 100 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'LEVOFLOXACINA COMPRIMIDO 500 MG ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ABENDAZOL SUSPENSION 200 ML/5 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'PARACETAMOL 1 GR X 100 COMP ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'DICLOFENACO POTASICO C/PARAC. X 100 COMP ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'DICLOFENACO 50 MG. x 1000 COMP ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GUANTES DESECHABLES TALLA S ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GUANTES DESECHABLES TALLA XS ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'EQUIPO SUERO PREMIER C/ALITA X20 UND ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GUANTES QUIRURGICOS PREM. Nro. 7 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GUANTES DESECHABLES TALLA M ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GUANTES DESECHABLES TALLA L ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GUANTES QUIRURGICOS PREM. Nro. 7 1/2 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GUANTES QUIRURGICOS PREM. Nro. 6 1/2 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BARBIJOS PREMIER DESCARTABLES X 50 PIEZAS ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'JERINGAS PREMIER 3 ML x 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'JERINGAS PREMIER 5 ML x 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'JERINGAS PREMIER 10 ML x 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'JERINGAS PREMIER 20 ML x 50 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS ELASTICAS PREM. 5CM x 12 Un. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS ELASTICAS PREM. 7.5CM x 12 Un. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS ELASTICAS PREM. 10CM x 12 Un. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALGODÓN N PREMIER DE 10 GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALGODÓN N PREMIER DE 50 GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALGODÓN N PREMIER DE 100 GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALGODÓN N PREMIER DE 200 GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALGODÓN N PREMIER DE 400 GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'COMPRESAS GASAS PREMIER 5CM x 40 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'COMPRESAS GASAS PREMIER 7.5CM x 40 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'COMPRESAS GASAS PREMIER 10CM x 40 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GASAS HOSPITALARIAS PREMIER (20 X 24) 20 YDS ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS GASA PREMIER 5CM x 10 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS GASA PREMIER 7.5CM x 10 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS GASA PREMIER 10CM x 12UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS GASA PREMIER 15CM x 10 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS GASA PREMIER 20CM x 5 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS ELASTICAS PREM. 15CM X 12 Un. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GUANTES QUIRURGICOS PREM. Nro. 6 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GUANTES QUIRURGICOS PREM. Nro. 8 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'JERINGAS PREMIER DE INSULINA ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'GASA HOSPITALARIA 150 YDS I (20 X 24) ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'EQUIPO SUERO PREMIER C/AGUJA X 20 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'EQUIPO SUERO PREMIER S/AGUJA X 20 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS ELASTICAS PREM. 20CM X 6 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS DE GASA 20 CM x 6 und. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS DE GASA 5 CM x12 und. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VENDAS DE GASA 7.5 cm x 12 und ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALCOHOL 70% TELCHI 120ML X 12 ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALCOHOL 70% TELCHI X 1L. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CLORURO DE MAGNESIO X 33GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ESENCIA COCO 30 ML X 6 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ESENCIA MOCOCHINCHI 30 ML X 6 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'TALCO TELCHI BYMIC X 100GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'FORMOL TELCHI x 1000 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALCOHOL TEL. YODADO x 125 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'POVIDINE TEL. YODADO x 120ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ESENCIA FRUTILLA 250 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CELINA GEL REAFIRMANTE 250 GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CELINA CREMA PARAFINA 250 GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CELINA LOCION REDUCTORES 125 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'SULFATO DE COBRE 1 KG ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'SULFATO DE ALUMINIO 1 KG ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CLORO 1 KG ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VASELINA SOLIDA 14 GR X 12 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VASELINA LIQUIDA 30 ML X 12 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'PASTA DE AGUA 200 GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'LOCION LITEL 200 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BRONCEADOR DE URUCU CREMA 200 GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BRONCEADOR DE URUCU ACEITE 200 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BRONCEADOR DE URUCU ACEITE 100 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'TINTURA DE YODO 30 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AROCARBOL EXPENDEDOR x 320 COMP ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AROCARBOL GOTAS 30ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AROCARBOL GOTAS 60ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BIO - SEP SOLUCION 30 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BIO - SEP SOLUCION 900 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'EXTRACTO DE PROPOLEO 20Ml ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'LUBYLAX JALEA 200 GR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'TUSIVAL ELIXIR 120 Gr ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VERRUBOL TÓPICO 10 ML. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VITAMINA C EXPENDEDOR x 320 PAST ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'AROCARBOL INSTANTANEO x 50 SOBRES ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VITAMINA CAMU CAMU x 10 SOBR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BIO-SEP CLEAN DE 250 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALOE VALENCIA CON STEVIA ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ALOE VALENCIA x 1000ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BIO-SEP GOTAS 90 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'BIO-SEP CLEAN x 60 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'TUSIVAL PASTILLA 4 UNID x PAQ 100 SOBRES ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MAGYQ ENERGIZANTE PET 300 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CHIAVAL ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MUESTRA MED. AROCARBOL GOTAS 30ML. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MUESTRA MED. EXTRACTO PROPOLEO 10ML. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'DOCTOR C DE 100 UNID ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'ENVASE TUSIVAL PASTILLAS (PLASTICO) ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MUESTRA MED. TUSIVAL ELEXIR ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MUESTRA MED. MAGYQ ENERGIZANTE 300ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MUESTRA MED. ALOE NORMAL 500 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CAMPERA TALLA XL ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CAMPERA TALLA M ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'CAMPERA TALLA L ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'VITAMINA C EXP. BLISTER x 1000 UND. ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'KIT DE ESCRITORIO ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MUESTRA MEDICA AROCARBOL SOBRE x UND ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MUESTRA MEDICA TUSIVAL PAST. x UND ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MUESTRA MEDICA LUBYLAX JALEA ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MUESTRA MEDICA BIO SEP SOLUCION 30 ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'MUESTRA MEDICA BIO-SEP CLEAN 60ml ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 
    App\Product::create([       'name' => 'PROPOVAL FRASCO X 20ML ',       'catalog_product_id'=>1,       'description' => '',       'state' => 'ACTIVO'     ]); 

    //INSUMOS
    App\Product::create([       'name' => 'SHAMPOO BBYL MANZANILLA 270ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND BBYL MANZANILLA 410ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PACK SHAMPOO+ACOND ARGAN 410ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'EMULSIONADO BBYL NEUTRO 410ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'TALCO CERO ANTIBACTERIAL 60GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'TALCO CERO ANTIBACTERIAL FRESH 60GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'EMULSIONADO BBYL NEUTRO 700 ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'JABON BBYL GLICERINA RPTO 750 ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'KY GEL LUBRICANTE 100 GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'VEET CREMA PIEL NORMAL 100 ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'VEET CREMA PIEL SENSIBLE 100ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO BBYL EVITA LAG 270ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'DETERGENTE EN POLVO LAV MAQ 6 KL',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'DETERGENTE EN POLVO LAV MAQ 800GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO GRANADA BIO 200ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO ARGAN OLIVA BIO 200ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'MUESTRA EMULSIONADO BBYL 120ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'MUESTRA COLONIA BBYL 120ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO BBYL EVITA LAGR 700ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'TALCO CERO ANTIBACTERIAL 120GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'TALCO CERO ANTIBACTERIAL FRESH 120GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO BBYL EVITA LAGR 270ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'COLONIA BBYL AMARILLA 260ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'BRASSO BRILLOMETAL 70 GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SUAVIZANTE FLORES SILVESTRES 900CC',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'QUERUBIN AEROSOL LAVANDA 220GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO BBYL MANZANILLA 410ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO BBYL PH BALANCEADO 410ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND BBYL CLASICO 270ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND BBYL CLASICO 410ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND BBYL MANZANILLA 270ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACEITE BBYL RELAX 210 ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO BBYL MANZANILLA 700 ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO BBYL EVITA LAGR 410ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'APARATO AUTOMATICO AIR WICK',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'QUERUBIN AEROSOL FLORAL 220GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'DETERGENTE POLVO LAV MAQ 3KL',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'DETERGENTE POLVO LAV MANO 800GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'DETERGENTE POLVO LAV MANO 3KL',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'AROMATIZADOR FRESH LIMON 220CC',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'AROMATIZADOR FRESH CHOCOLATE 220CC',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'AROMATIZADOR FRESH F.SILVESTRES 220CC',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPO MAQUI BIO 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'AROMATIZADOR FRESH MARINO 220CC',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND. MAQUI BIO 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'AIR WICK MATIC BOSQUE MAGICO',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'AIR WICK FRESH MATIC LAVANDA',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'AIR WICK FRESH MATIC CITRICO',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX DILUIBLE JARDIN 5LT',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX DILUIBLE MARINA 5LT',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX DILUIBLE LAVANDA 5LT',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'AIR WICK FRESH MATIC VAINILLA',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SUAVIZANTE FLORES SILVESTRES 3LT',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACEITE DE OLIVA YBARRA PURO 250ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACEITE DE OLIVA YBARRA LATA 200ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACEITE YBARRA EXTRA VIRGEN 250ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PACK SHAMPOO+ACOND PROPOLEO JALEA',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PACK SHAMPOO+ACOND MAQUI 410ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PACK SHAMPOO+ACOND PALTA OLIVA',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'CITRONELA MATA ZANCUDOS',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'MUESTRAS SHAMPOO NEUTRO 120ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'LOCION CREMA HUMECTANTE 270ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'TALCO BBYL 200GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'COLONIA BBYL CELESTE 260ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'COLONIA BBYL VERDE 260ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'COLONIA BBYL ROSADA 260ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'COLONIA BBYL LILA 260ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'CURA CB STANDARD CAJA X 100 UNID',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'MICROPOROSO PIEL 1.25 X 9 M (24 UNID)',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'MICROPOROSO PIEL 2.50 X 9 M (12 UNID)',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ESTUCHE BBYL VERDE',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'VANISH LIQUIDO PACK ROSA 650ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'MICROPOROSO PIEL 5 X 9 M (6 UNID)',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ESTUCHE BBYL PINK',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO BBYL PH BALANCEADO 700ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'VANISH LIQUIDO PACK BLANCO 650 ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO MANZANILLA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO MANZANA PAPAYA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO LECHE COCO 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO GRANADA UVA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO ARGAN OLIVA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO QUILLAY 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO ARANDANO UVA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND MANZANILLA 750 ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND MANZANA PAPAYA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND LECHE COCO 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND GRANADA UVA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND ARGAN OLIVA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND ARANDANO UVA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PACK SHAMPOO+ACOND GRANADA UVA 410ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PACK SHAMPOO+ACOND ARANDANO 410ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PACK SHAMPOO+ACOND MANZANILLA 410ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'COLONIA BBYL PINK 260ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SANITIZANTE PARA MANOS 75ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SANITIZANTE PARA MANOS 300ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SANITIZANTE PARA MANOS 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO MORINGA BIO 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO PALTA OLIVA BIO 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SHAMPOO PROPOLEO JALEA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND MORINGA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND PALTA OLIVA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'ACOND PROPOLEO JALEA 750ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'EMULSIONADO BBYL NEUTRO 270ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'JABON LIQUIDO LAVANDA 700 ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX BLANCO 900ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX BLANCO 1800ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX BLANCO 5 LTRS',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'HARPIC LAVANDINA 500ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'HARPIC EXTRA FUERTE 500ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'HARPIC POWER PLUS CITRICO 500ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX PRIMAVERA 900ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX JAZMIN 1800ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX MARINA 5 LTRS',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'SUAVIZANTE QUERUBIN 900ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'TERMO PREMIUM 4.3 LTRS',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX GOLD COCINA G. 500ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX GOLD COCINA S. 420ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX GOLD BAÑO G. 500ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'PROCENEX GOLD BAÑO S. 420ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'AIR WICK REPUESTO 250ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'MUESTRA SHAMPOO MANZANILLA 200ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'VANISH ROSA POLVO 900 GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'VANISH ROSA POLVO 450 GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'JABON LIQ. MANZANA PAPAYA 300ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'VANISH LIQUIDO PACK ROSA 400ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'VANISH LIQUIDO PACK BLANCO 400ML',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    App\Product::create([       'name' => 'VANISH BLANCO POLVO 450 GR',       'catalog_product_id'=>2,       'description' => ' ',       'state' => 'ACTIVO'     ]);
    
  }
}
